// import React, { Suspense } from 'react'
// import { useLoader } from '@react-three/fiber'
// import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
// import { useGLTF } from '@react-three/drei'
// function Model() {
//   const gltf = useGLTF("https://arflutterapp.s3.eu-north-1.amazonaws.com/kfccompressgltf.glb")
//   // const gltf = useLoader(GLTFLoader,"/models/druid.gltf")
//   console.log(gltf,"gltf")
//   return (
//   //  <Suspense fallback = {null}>
//     <primitive object={gltf.scene} />
//   //  </Suspense>
//   )
// }

// export default Model


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/model/koreanwinggltf.gltf')
  console.log(nodes, materials,"nodes and materials")
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0007.geometry}
        material={materials['Material_0.008']}
      />
    </group>
  )
}

useGLTF.preload('/model/koreanwingglft.glft')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
//         import React, { useRef } from 'react'
//         import { useGLTF, 
        
//         useAnimations } from '@react-three/drei'
        
        
//         export default function Model(props) {
//           const group = useRef()
//           const { nodes, materials, animations } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/druid/model.gltf')
// const { actions } = useAnimations(animations, group)
//           return (
//             <group ref={group} {...props} dispose={null}>
//         <group scale={1.91} >
// <primitive object={nodes.root} />
// <skinnedMesh geometry={nodes.druid.geometry} material={materials.color_main} skeleton={nodes.druid.skeleton} />
// </group>

//             </group>
//           )
//         }

// useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/druid/model.gltf')